### PR TITLE
Ability to configure per environment

### PR DESCRIPTION
**Pull request by kennydeckers**
This adds the ability to put environment-specific configuration in the _app/etc/env.php_

### CODE REVIEW

**Comment by srenon** [comment]
@kennydeckers ... sorry for the delay. What version of Magento was this introduces in? Was it 2.2.x? if so then I will need to stop supporting older version by update the composer requirements

**Comment by kennydeckers** [comment]
> @kennydeckers ... sorry for the delay. What version of Magento was this introduces in? Was it 2.2.x? if so then I will need to stop supporting older version by update the composer requirements

I'm pretty sure this has been around since Magento 2.1 but since the official developer documentation of that version has been removed I can't confirm 100%. As far as I'm aware Magento also no longer provides support for 2.1 (and 2.2) so it would kind of make sense to "up" the requirement to 2.3 and up?

**Comment by kennydeckers** [comment]
@srenon bump?

**Comment by srenon** [comment]
@kennydeckers... I will create a new release shortly

**Pull request merged**
