### PR TITLE
Remove unused and uneeded dependency

### PR DESCRIPTION
**Pull request by thomas-kl1**

### CODE REVIEW

**Comment by srenon** [comment]
@thomas-kl1 ... with 34+ different extensions it is becoming increasingly difficult to constantly maintain the same code (like adding a tab to store configuration in system.xml, getting module version, constantly answering emails & chats about what is the latest version of our extension... etc). Going forward a lot of this functionality will be moving to our "core" extension

**Comment by thomas-kl1** [comment]
> with 34+ different extensions it is becoming increasingly difficult to constantly maintain the same code
- Adding an other "base" module is worse to maintain whole code then.

>adding a tab to store configuration in system.xml
- It's not diffucult at all

> constantly answering emails & chats about what is the latest version of our extension... etc
- I don't get the point with the code, it's more about a bad documentation/faq on your own

- adding a dependency but which is never used in the code is wrong, it's like "hey I'm adding some obscure stuff, but don't worry"

**Comment by srenon** [comment]
@thomas-kl1...

Sorry, you feel that way. If you take a Magento there are at least 3 different implementations of 'json_decode' which make it very difficult to create an extension that supports all versions without maintain multiple branches or write my own custom implementation. So our base extension will be used as a helper to prevent us from having multiple variations of the same code as we refactor for 2.4.0.

All of these modules use the same files and over the years they are all slightly different.

https://github.com/magepal/magento2-custom-shipping-rate/blob/master/Block/Adminhtml/System/Config/Form/Composer/Version.php

https://github.com/magepal/magento2-gmail-smtp-app/blob/master/Block/Adminhtml/System/Config/Form/Composer/Version.php

https://github.com/magepal/magento2-google-tag-manager/blob/master/Block/Adminhtml/System/Config/Form/Composer/Version.php


All our extensions display the version numbers.
image

**Comment by thomas-kl1** [comment]
I mean "suggest" in composer is exactly the right place for this dependency, not in require...

**Pull request closed without merging**
